
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - ./models:/app/backend/models
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - .env
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    container_name: streamlit_ui
    # streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - .env
    depends_on:
      - mongodb
      - backend
    stdin_open: true
    tty: true

  mongodb:
    image: mongo:7
    container_name: mongodb 
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8888:8081"
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb  
    env_file:
      - .env

volumes:
  mongo_data:
