
services: 
  matcher-api:
    container_name: jobs_matcher
    build: ./knowledge_base
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models # Mounts local ./models to /app/models in container
