


services:
  job-matcher:
    container_name: job-matcher
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - vectorstore:/app/vectorstore
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app

  llama-server:
    container_name: llama-server
    build:
      context: .
      dockerfile: ./backend/models/Dockerfile
    volumes:
      - ./models/mistral-7b-instruct-v0.2.Q4_K_M.gguf:/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf:ro
    ports:
      - "8001:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 8g
    environment:
      - MODEL=/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf

volumes:
  vectorstore:

